foodapp/food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:course_id>/',views.detail,name='detail'),
    path('courses/',views.courses,name='courses'),
    path('add/',views.create_course,name='create_course'),
    path('update/<int:id>/',views.update_course,name="update_course"),
    path('delete/<int:id>/',views.delete_course,name='delete_course'),
]

foodapp/foodapp/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('subjects/',include('food.urls'))
]

foodapp/food/models.py
from django.db import models

# Create your models here.
class course(models.Model):

    def __str__(self):
        return self.course_name

    course_name = models.CharField(max_length=200)
    course_desc = models.CharField(max_length=200)
    course_price = models.IntegerField()
    course_image = models.CharField(max_length=500,default="https://asdicourse.com/default.svg")

foodapp/food/forms.py
from django import forms
from .models import course

class CourseForm(forms.ModelForm):
      class Meta:
            model = course
            fields = ['course_name','course_desc','course_price','course_image']

foodapp/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import course
from django.template import loader
from .forms import CourseForm
# Create your views here.

def index(request):
    course_list = course.objects.all()
    context = {
        'course_list':course_list,
    }
    return render(request,'food/index.html',context)

def courses(request):
    return HttpResponse("This is an Course view")


def detail(request,course_id):
    course_del = course.objects.get(pk=course_id)
    context = {
        'course':course_del,
    }

    return render(request,'food/detail.html',context)

def create_course(request):
    form = CourseForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/course-form.html',{'form':form})

def update_course(request,id):
    course_update = course.objects.get(id=id)
    form = CourseForm(request.POST or None, instance=course_update)

    if form.is_valid():
        form.save()
        return redirect("food:index")
    
    return render(request,'food/course-form.html',{'form':form,'course': course})

def delete_course(request,id):
    course_del = course.objects.get(id=id)
    if request.method == "POST":
        course_del.delete()
        return redirect('food:index')

    return render(request,'food/course-delete.html',{'course_del':course_del})

foodapp/food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Courses List</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <title>Document</title>
</head>
<body>
      <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Courses app</a>

            <div class="navbar">
                  <a class="nav-item nav-link link-primary" href="{% url 'food:create_course' %}">Add-Courses</a>
                  <a class="nav-item nav-link link-primary" href="#">Delete-courses</a>
                  <a class="nav-item nav-link link-primary" href="#">View-courses</a>
            </div>
      </nav>

      {% block body %}
      {% endblock %}
</body>
</html>

foodapp/food/templates/food/course-delete.html
<form method="POST">
      {% csrf_token %}
      <h2>Are you sure you want to delete {{ course.course_name }}</h2>
      <button type="submit">Confirm</button>
</form>

foodapp/food/templates/food/course-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
      {% csrf_token %}
      {{form}}
      <button type="submit">Save</button>
</form>
{% endblock %}

foodapp/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<br/>
<div class="container">
      <div class="row">
            <div class="col-md-6">
                  <img  src="{{course.course_image}}" height="300px" class="card"/>
            </div>
            <div class="col-md-6">
                  <h1>{{ course.course_name }}</h1>
                  <h2>{{ course.course_desc }}</h2>
                  <h3>{{ course.course_price }}</h3>
                  <a href="{% url 'food:delete_course' course.id %}">Delete</a>
            </div>
      </div>
</div>



{% endblock %}

foodapp/food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Courses List</title>

</head>
<body>
      
      {% block body %}
      <br/>
      {% for course in course_list %}
            <div class="row">
                  <div class="col-md-3 offset-md-2">
                        <img height="200px" class="card"  src="{{course.course_image}}"/>
                  </div>
                  <div class="col-md-4">
                        <h3>{{ course.course_name }}</h3>
                        <h5>{{ course.course_desc }}</h5>
                        <h6>${{ course.course_price }}</h6>
                  </div>
                  <div class="col-md-2">
                        <a href="{% url 'food:detail' course.id %}" class="btn btn-success">Details</a>
                  </div>
            </div>


      {% endfor %}
      {% endblock %}
      
      this is the old code
      
      <ul>
            <li>
                  <a href="">{{ course.id }} -- {{ course.course_name }}</a>
            </li>
      </ul>

</body>
</html>